### ISSUE TITLE
Rotated-MNIST, Permuted-MNIST

### ISSUE THREAD

**Issue by shikhar-srivastava** [pranshu28/TAG#2]
Hi Pranshu, 

Thanks for this very interesting work, and for sharing the code. 

I'm wondering if you've tried TAG on simpler tasks like Rotated/Permuted-MNIST? Specifically, I am trying to infer if the adaptation trajectories carry information about the different rotation/pixel-permutation b/w tasks.

Thanks in advance,
Shikhar

**Comment by pranshu28** [comment]
Hi Shikhar,

Yes, I have tried TAG on Rotated/Permuted-MNIST. From a brief analysis, we found that TAG was able to recognize the similarity between rotated images specially. I will update the code for MNIST-based datasets soon but you can also borrow it from the existing works mentioned in the README.md.

**Comment by shikhar-srivastava** [comment]
Thank you for your quick response, @pranshu28.

**Comment by htsplex** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
Wind561, @harry4707, @zhengxixuan, @mrmading, @neohope, @donkko, @mohsinhijazee, @0x0918, @williamjqk, @SlashNephy, @AlisterTA, @captainaadesh, @0xharib, @prakashujjwal1010, @weishengmin, @LevYas, @feifanzhou, @lemonnight, @vincentperot, @JediChou, @Seokhyeon315, @janlesko, @TrevorSmale, @AubreyHewes, @mahingupta, @zeequn, @leonsal, @Saladino93, @server321, @bajian, @slempke, @Keeeeen, @pogba1990, @chyidl, @stijn-de-wit, @Barbarbarb01, @eepaul, @dennisXZX, @irvingmao9225, @drchrispinnock, @tjfreitas, @AL04, @npcheng, @MekkyMayata, @1Jack2, @fengxiaoiie, @edinsoncs, @jonmarrs, @selevit, @jexchan
